#!/bin/bash

set -e

sinter collect \
    --circuits out/circuits/code_name=* \
    --save_resume_filepath out/stats.csv \
    --metadata_func auto \
    --decoders pymatching \
    --max_shots 100_000 \
    --max_errors 100 \
    --processes 10 \


