#!/bin/bash

set -e

sinter collect \
    --circuits out/circuits/code_name=GaugeHoneycombCode*.stim \
    --save_resume_filepath out/stats.csv \
    --metadata_func auto \
    --decoders pymatching \
    --max_shots 10_000 \
    --max_errors 100 \
    --processes 1 \

    # --circuits out/circuits/code_name=GaugeFloquetColourCode,per=0.001,px=1.0,py=1.0,pz=1.0,pm=1.0,distance=12,gf_0=2,gf_1=3,gf_2=0.stim \
