#!/bin/bash 

set -e 

parallel -q --ungroup ./generate_circuits.py \
    --code_name {1} \
    --per 0.001 \
    --px 1\
    --py 1\
    --pz {2}\
    --pm {3}\
    --distance {4} \
    --gf_1 {5} \
    --gf_2 {6} \
    --gf_3 {7} \
    ::: "GaugeHoneycombCode" \
    ::: 1 4 8 \
    ::: 1 4 8\
    ::: 4 8 12 \
    ::: 1 2 3\
    ::: 1 2 3\
    ::: 1 2 3\


parallel -q --ungroup ./generate_circuits.py \
    --code_name {1} \
    --per 0.001 \
    --px 1\
    --py 1\
    --pz {2}\
    --pm {3}\
    --distance {4} \
    --gf_1 {5} \
    --gf_2 {6} \
    ::: "GaugeFloquetColourCode" \
    ::: 1 4 8 \
    ::: 1 4 8\
    ::: 4 8 12 \
    ::: 1 2 3\
    ::: 1 2 3\
