#!/bin/bash 

set -e 

# parallel -q --ungroup ./generate_circuits.py \
#     --code_name {1} \
#     --per 0.001 \
#     --px 1 \
#     --py 1 \
#     --pz 1 \
#     --pm {2} \
#     --distance {3} \
#     --gf_1 {4} \
#     --gf_2 {5} \
#     --gf_3 {6} \
#     ::: "GaugeHoneycombCode" \
#     ::: 1 \
#     ::: 12 \
#     ::: 3 \
#     ::: 3 \
#     ::: 2 \

parallel -q --ungroup ./generate_circuits.py \
    --code_name {1} \
    --per 0.001 \
    --px 1 \
    --py 1 \
    --pz 1 \
    --pm {2} \
    --distance {3} \
    --gf_1 {4} \
    --gf_2 {5} \
    ::: "GaugeFloquetColourCode" \
    ::: 1 \
    ::: 12 \
    ::: 2 \
    ::: 3 \